-- POBLAR CATALOGO DE EJERCICIOS
DELETE FROM catalogo_ejercicios;

INSERT INTO catalogo_ejercicios (id, nombre, musculo_principal, equipamiento, categoria) VALUES
('cables_cruzados', 'Cables cruzados', 'Pecho', '', 'Pecho'),
('curl_de_biceps', 'Curl de bíceps', 'Bíceps', 'mancuerna', 'Bíceps'),
('curl_de_pierna_acostado', 'Curl de pierna acostado', 'Isquiotibiales', 'máquina', 'Isquiotibiales'),
('extension_de_pierna', 'Extensión de pierna', 'Cuádriceps', '', 'Cuádriceps'),
('remo_sentado_con_agarre_en_v', 'Remo sentado con agarre en v', 'Espalda Superior', 'cable', 'Espalda Superior'),
('tiron_a_la_cara', 'Tirón a la cara', 'Hombros', '', 'Hombros'),
('curl_de_biceps_2', 'Curl de bíceps 21', 'Bíceps', '', 'Bíceps'),
('abdominales_tijera', 'Abdominales tijera', 'Abdominales', '', 'Abdominales'),
('rueda_abdominal', 'Rueda abdominal', 'Abdominales', '', 'Abdominales'),
('aerobics', 'Aerobics', 'Cardio', '', 'Cardio'),
('bicicleta_de_aire', 'Bicicleta de aire', 'Cardio', '', 'Cardio'),
('arnold_press', 'Arnold press', 'Hombros', 'mancuerna', 'Hombros'),
('alrededor_del_mundo', 'Alrededor del mundo', 'Pecho', '', 'Pecho'),
('sentadilla_pistol_asistida', 'Sentadilla pistol asistida', 'Cuádriceps', '', 'Cuádriceps'),
('extension_de_espalda', 'Extensión de espalda', 'Espalda Baja', 'máquina', 'Espalda Baja'),
('extension_de_espalda_2', 'Extensión de espalda', 'Espalda Baja', 'hipertensión', 'Espalda Baja'),
('extension_de_espalda_3', 'Extensión de espalda', 'Espalda Baja', 'hipertensión con peso', 'Espalda Baja'),
('ball_slams', 'Ball slams', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('aperturas_con_banda', 'Aperturas con banda', 'Hombros', '', 'Hombros'),
('cuerdas_de_batalla', 'Cuerdas de batalla', 'Cardio', '', 'Cardio'),
('curl_de_biceps_detras_de_la_espalda', 'Curl de bíceps detrás de la espalda', 'Antebrazos', 'barra', 'Antebrazos'),
('curl_por_detras_de_la_espalda', 'Curl por detrás de la espalda', 'Bíceps', 'polea', 'Bíceps'),
('sentadilla_con_cinturon', 'Sentadilla con cinturón', 'Cuádriceps', 'máquina', 'Cuádriceps'),
('fondos_en_banco', 'Fondos en banco', 'Tríceps', '', 'Tríceps'),
('press_de_banca__agarre_cerrado', 'Press de banca - agarre cerrado', 'Tríceps', 'barra', 'Tríceps'),
('press_de_banca__agarre_abierto', 'Press de banca - agarre abierto', 'Pecho', 'barra', 'Pecho'),
('press_de_banca', 'Press de banca', 'Pecho', 'barra', 'Pecho'),
('press_de_banca_2', 'Press de banca', 'Pecho', 'cable', 'Pecho'),
('press_de_banca_3', 'Press de banca', 'Pecho', 'mancuerna', 'Pecho'),
('press_de_banca_4', 'Press de banca', 'Pecho', 'máquina Smith', 'Pecho'),
('remo_inclinado', 'Remo inclinado', 'Espalda Superior', 'banda', 'Espalda Superior'),
('remo_inclinado_2', 'Remo inclinado', 'Espalda Superior', 'barra', 'Espalda Superior'),
('remo_inclinado_3', 'Remo inclinado', 'Espalda Superior', 'mancuerna', 'Espalda Superior'),
('curl_de_biceps_3', 'Curl de bíceps', 'Bíceps', 'barra', 'Bíceps'),
('curl_de_biceps_4', 'Curl de bíceps', 'Bíceps', 'máquina', 'Bíceps'),
('curl_de_biceps_5', 'Curl de bíceps', 'Bíceps', 'suspensión', 'Bíceps'),
('abdominales_bicicleta', 'Abdominales bicicleta', 'Abdominales', '', 'Abdominales'),
('abdominales_bicicleta_piernas_levantadas', 'Abdominales bicicleta piernas levantadas', 'Abdominales', '', 'Abdominales'),
('perro_de_caza', 'Perro de caza', 'Glúteos', '', 'Glúteos'),
('salto_al_cajon', 'Salto al cajon', 'Cuádriceps', '', 'Cuádriceps'),
('sentadilla_al_cajon', 'Sentadilla al cajon', 'Cuádriceps', 'barra', 'Cuádriceps'),
('boxeo', 'Boxeo', 'Cardio', '', 'Cardio'),
('sentadilla_bulgara', 'Sentadilla búlgara', 'Cuádriceps', '', 'Cuádriceps'),
('burpee', 'Burpee', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('burpee_sobre_la_barra', 'Burpee sobre la barra', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('mariposa', 'Mariposa', 'Pecho', 'Pec Deck', 'Pecho'),
('press_pallof_con_cable', 'Press pallof con cable', 'Abdominales', '', 'Abdominales'),
('abdominal_corto_con_cable', 'Abdominal corto con cable', 'Abdominales', '', 'Abdominales'),
('tiron_con_poleas_entre_piernas', 'Tirón con poleas entre piernas', 'Glúteos', '', 'Glúteos'),
('giro_con_cable_de_arriba_hacia_abajo', 'Giro con cable de arriba hacia abajo', 'Abdominales', '', 'Abdominales'),
('extension_de_pantorrilla', 'Extensión de pantorrilla', 'Gemelos', 'máquina', 'Gemelos'),
('press_de_pantorrilla', 'Press de pantorrilla', 'Gemelos', 'máquina', 'Gemelos'),
('fondos', 'Fondos', 'Pecho', '', 'Pecho'),
('fondos_asistidos', 'Fondos asistidos', 'Pecho', '', 'Pecho'),
('fondos_con_peso_anadido', 'Fondos con peso añadido', 'Pecho', '', 'Pecho'),
('apertura', 'Apertura', 'Pecho', 'banda', 'Pecho'),
('apertura_2', 'Apertura', 'Pecho', 'mancuerna', 'Pecho'),
('apertura_3', 'Apertura', 'Pecho', 'máquina', 'Pecho'),
('apertura_de_pecho', 'Apertura de pecho', 'Pecho', 'suspensión', 'Pecho'),
('press_de_pecho', 'Press de pecho', 'Pecho', 'banda', 'Pecho'),
('press_de_pecho_2', 'Press de pecho', 'Pecho', 'máquina', 'Pecho'),
('remo_inclinado_con_apoyo_de_pecho', 'Remo inclinado con apoyo de pecho', 'Espalda Superior', 'mancuerna', 'Espalda Superior'),
('vuelos_posteriores', 'Vuelos posteriores', 'Hombros', 'mancuerna', 'Hombros'),
('elevacion_en_y_con_soporte_en_el_pecho', 'Elevación en y con soporte en el pecho', 'Hombros', 'mancuerna', 'Hombros'),
('dominadas_chin_up', 'Dominadas Chin Up', 'Dorsales', '', 'Dorsales'),
('dominadas_chin_up_asistida', 'Dominadas Chin Up asistida', 'Dorsales', '', 'Dorsales'),
('dominadas_chin_up_con_peso', 'Dominadas Chin Up con peso', 'Dorsales', '', 'Dorsales'),
('almeja', 'Almeja', 'Glúteos', '', 'Glúteos'),
('flexiones_con_palmada', 'Flexiones con palmada', 'Pecho', '', 'Pecho'),
('clean', 'Clean', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('clean_and_jerk', 'Clean and Jerk', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('cargada_y_press', 'Cargada y press', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('cargada_y_tiron', 'Cargada y tiron', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('escalada', 'Escalada', 'Cardio', '', 'Cardio'),
('curl_de_concentracion', 'Curl de concentración', 'Bíceps', '', 'Bíceps'),
('curl_de_martillo_cruzado', 'Curl de martillo cruzado', 'Bíceps', '', 'Bíceps'),
('abdominal_corto', 'Abdominal corto', 'Abdominales', '', 'Abdominales'),
('abdominal_corto_2', 'Abdominal corto', 'Abdominales', 'máquina', 'Abdominales'),
('abdominal_corto_3', 'Abdominal corto', 'Abdominales', 'con peso añadido', 'Abdominales'),
('zancada_curtsy', 'Zancada curtsy', 'Cuádriceps', 'mancuerna', 'Cuádriceps'),
('bicicleta', 'Bicicleta', 'Cardio', '', 'Cardio'),
('dead_bug', 'Dead bug', 'Abdominales', '', 'Abdominales'),
('dead_hang', 'Dead hang', 'Espalda Superior', '', 'Espalda Superior'),
('peso_muerto', 'Peso muerto', 'Glúteos', 'banda', 'Glúteos'),
('peso_muerto_2', 'Peso muerto', 'Glúteos', 'barra', 'Glúteos'),
('peso_muerto_3', 'Peso muerto', 'Glúteos', 'mancuerna', 'Glúteos'),
('peso_muerto_smith', 'Peso muerto Smith', 'Glúteos', 'máquina', 'Glúteos'),
('peso_muerto_4', 'Peso muerto', 'Trapecio', 'barra', 'Trapecio'),
('peso_muerto_con_tiron_alto', 'Peso muerto con tiron alto', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('press_de_banca_en_declive', 'Press de banca en declive', 'Pecho', 'barra', 'Pecho'),
('press_de_banca_en_declive_2', 'Press de banca en declive', 'Pecho', 'mancuerna', 'Pecho'),
('press_de_banca_en_declive_3', 'Press de banca en declive', 'Pecho', 'máquina', 'Pecho'),
('press_de_banca_en_declive_smith', 'Press de banca en declive Smith', 'Pecho', 'máquina', 'Pecho'),
('apertura_declinada', 'Apertura declinada', 'Pecho', 'mancuerna', 'Pecho'),
('abdominal_corto_en_banco_inclinado', 'Abdominal corto en banco inclinado', 'Abdominales', '', 'Abdominales'),
('abdominal_corto_en_banco_inclinado_2', 'Abdominal corto en banco inclinado', 'Abdominales', 'con peso añadido', 'Abdominales'),
('flexion_declinada', 'Flexion declinada', 'Pecho', '', 'Pecho'),
('flexiones_diamante', 'Flexiones diamante', 'Tríceps', '', 'Tríceps'),
('postura_del_perro_cabeza_abajo', 'Postura del perro cabeza abajo', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('drag_curl', 'Drag curl', 'Bíceps', '', 'Bíceps'),
('dragon_flag', 'Dragón flag', 'Abdominales', '', 'Abdominales'),
('dragonfly', 'Dragónfly', 'Abdominales', '', 'Abdominales'),
('remo_con_mancuerna', 'Remo con mancuerna', 'Dorsales', '', 'Dorsales'),
('arrancada_con_mancuerna', 'Arrancada con mancuerna', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('press_de_apreton_con_mancuernas', 'Press de apretón con mancuernas', 'Pecho', '', 'Pecho'),
('step_con_mancuerna', 'Step con mancuerna', 'Cuádriceps', '', 'Cuádriceps'),
('rodillas_a_codos', 'Rodillas a codos', 'Abdominales', '', 'Abdominales'),
('entrenador_eliptico', 'Entrenador eliptico', 'Cardio', '', 'Cardio'),
('curl_con_barra_ez', 'Curl con barra ez', 'Bíceps', '', 'Bíceps'),
('paseo_del_granjero', 'Paseo del granjero', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('press_de_banca_con_pies_elevados', 'Press de banca con pies elevados', 'Pecho', 'barra', 'Pecho'),
('patadas_boca_de_incendio', 'Patadas boca de incendio', 'Glúteos', '', 'Glúteos'),
('press_de_suelo', 'Press de suelo', 'Pecho', 'barra', 'Pecho'),
('press_en_el_suelo', 'Press en el suelo', 'Pecho', 'mancuerna', 'Pecho'),
('fondos_de_triceps_en_suelo', 'Fondos de tríceps en suelo', 'Tríceps', '', 'Tríceps'),
('aleteo_de_piernas', 'Aleteo de piernas', 'Abdominales', '', 'Abdominales'),
('saltos_de_rana', 'Saltos de rana', 'Cuádriceps', '', 'Cuádriceps'),
('frog_pumps', 'Frog pumps', 'Glúteos', 'mancuerna', 'Glúteos'),
('front_lever_sostenida', 'Front lever sostenida', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('front_lever_elevacion', 'Front lever elevación', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('elevacion_frontal', 'Elevación frontal', 'Hombros', 'banda', 'Hombros'),
('elevacion_frontal_2', 'Elevación frontal', 'Hombros', 'barra', 'Hombros'),
('elevacion_frontal_3', 'Elevación frontal', 'Hombros', 'cable', 'Hombros'),
('elevacion_frontal_4', 'Elevación frontal', 'Hombros', 'mancuerna', 'Hombros'),
('elevacion_frontal_5', 'Elevación frontal', 'Hombros', 'suspensión', 'Hombros'),
('sentadilla_delantera', 'Sentadilla delantera', 'Cuádriceps', '', 'Cuádriceps'),
('sentadilla_profunda', 'Sentadilla profunda', 'Cuádriceps', '', 'Cuádriceps'),
('puente_de_gluteos', 'Puente de glúteos', 'Glúteos', '', 'Glúteos'),
('elevacion_de_gluteos_y_femorales', 'Elevación de glúteos y femorales', 'Isquiotibiales', '', 'Isquiotibiales'),
('patada_de_burro', 'Patada de burro', 'Glúteos', 'máquina', 'Glúteos'),
('patada_de_burro_2', 'Patada de burro', 'Glúteos', '', 'Glúteos'),
('sentadilla_globet', 'Sentadilla globet', 'Cuádriceps', '', 'Cuádriceps'),
('buen_dia', 'Buen dia', 'Isquiotibiales', 'barra', 'Isquiotibiales'),
('remo_gorila_pesa_rusa', 'Remo gorila pesa rusa', 'Espalda Superior', '', 'Espalda Superior'),
('sentadilla_hack', 'Sentadilla hack', 'Cuádriceps', '', 'Cuádriceps'),
('sentadilla_hack_2', 'Sentadilla hack', 'Cuádriceps', 'máquina', 'Cuádriceps'),
('curl_martillo', 'Curl martillo', 'Bíceps', 'banda', 'Bíceps'),
('curl_martillo_2', 'Curl martillo', 'Bíceps', 'cable', 'Bíceps'),
('curl_martillo_3', 'Curl martillo', 'Bíceps', 'mancuerna', 'Bíceps'),
('equilibrio_invertido', 'Equilibrio invertido', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('flexiones_verticales', 'Flexiones verticales', 'Hombros', '', 'Hombros'),
('hang_clean', 'Hang clean', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('hang_snatch', 'Hang Snatch', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('levantamiento_de_rodillas_en_barra', 'Levantamiento de rodillas en barra', 'Abdominales', '', 'Abdominales'),
('levantamiento_de_piernas_en_barra', 'Levantamiento de piernas en barra', 'Abdominales', '', 'Abdominales'),
('abdominales_toque_al_talon', 'Abdominales toque al talon', 'Abdominales', '', 'Abdominales'),
('press_hexagonal', 'Press hexagonal', 'Pecho', 'mancuerna', 'Pecho'),
('elevacion_de_rodillas', 'Elevacion de rodillas', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('hiit', 'HIIT', 'Cardio', '', 'Cardio'),
('senderismo', 'Senderismo', 'Cardio', '', 'Cardio'),
('abduccion_de_caderas', 'Abduccion de caderas', 'Aductores', '', 'Aductores'),
('aduccion_de_caderas', 'Aduccion de caderas', 'Aductores', '', 'Aductores'),
('empuje_de_caderas', 'Empuje de caderas', 'Glúteos', '', 'Glúteos'),
('empuje_de_caderas_barra', 'Empuje de caderas barra', 'Glúteos', '', 'Glúteos'),
('impulso_de_cadera', 'Impulso de Cadera', 'Glúteos', 'Máquina', 'Glúteos'),
('elevacion_de_cadera', 'Elevación de cadera', 'Glúteos', 'Máquina Smith', 'Glúteos'),
('hollow_rock', 'Hollow Rock', 'Abdominales', '', 'Abdominales'),
('press_de_banca_inclinado', 'Press de Banca Inclinado', 'Pecho', 'Barra', 'Pecho'),
('press_de_banca_inclinado_2', 'Press de Banca Inclinado', 'Pecho', 'Mancuerna', 'Pecho'),
('press_de_banca_inclinado_3', 'Press de Banca Inclinado', 'Pecho', 'Máquina Smith', 'Pecho'),
('aperturas_inclinadas', 'Aperturas Inclinadas', 'Pecho', 'Mancuerna', 'Pecho'),
('press_de_pecho_inclinado', 'Press de Pecho Inclinado', 'Pecho', 'Máquina', 'Pecho'),
('flexiones_inclinadas', 'Flexiones Inclinadas', 'Pecho', '', 'Pecho'),
('remo_invertido', 'Remo Invertido', 'Espalda Superior', '', 'Espalda Superior'),
('press_de_pecho_isolateral', 'Press de Pecho Iso-Lateral', 'Pecho', 'Máquina', 'Pecho'),
('remo_alto_isolateral', 'Remo Alto Iso-Lateral', 'Dorsales', '', 'Dorsales'),
('remo_bajo_isolateral', 'Remo Bajo Iso-Lateral', 'Espalda Superior', '', 'Espalda Superior'),
('remo_isolateral', 'Remo Iso-Lateral', 'Espalda Superior', '', 'Espalda Superior'),
('jack_knife', 'Jack Knife', 'Abdominales', 'Suspensión', 'Abdominales'),
('press_jm', 'Press JM', 'Tríceps', 'Barra', 'Tríceps'),
('salto_a_la_cuerda', 'Salto a la cuerda', 'Cardio', '', 'Cardio'),
('encogimiento_de_hombros_con_salto', 'Encogimiento de Hombros con Salto', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('sentadilla_con_salto', 'Sentadilla con Salto', 'Cuádriceps', '', 'Cuádriceps'),
('jumping_jack', 'Jumping Jack', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('estocada_con_salto', 'Estocada con Salto', 'Cuádriceps', '', 'Cuádriceps'),
('pesa_rusa_alrededor_del_mundo', 'Pesa rusa alrededor del mundo', 'Hombros', '', 'Hombros'),
('cargada_con_pesa_rusa', 'Cargada con Pesa Rusa', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('curl_con_pesa_rusa', 'Curl con Pesa Rusa', 'Bíceps', '', 'Bíceps'),
('sentadilla_goblet_con_pesa_rusa', 'Sentadilla Goblet con Pesa Rusa', 'Cuádriceps', '', 'Cuádriceps'),
('halo_con_pesa_rusa', 'Halo con pesa rusa', 'Hombros', '', 'Hombros'),
('tiron_alto_con_pesa_rusa', 'Tirón Alto con Pesa Rusa', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('press_de_hombros_con_pesa_rusa', 'Press de Hombros con Pesa Rusa', 'Hombros', '', 'Hombros'),
('arrancada_con_pesa_rusa', 'Arrancada con Pesa Rusa', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('swing_con_pesa_rusa', 'Swing con Pesa Rusa', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('levantamiento_turco_con_pesa_rusa', 'Levantamiento Turco con Pesa Rusa', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('dominadas_con_kipping', 'Dominadas con Kipping', 'Dorsales', '', 'Dorsales'),
('rodillas_al_pecho_en_barras_paralelas', 'Rodillas al Pecho en Barras Paralelas', 'Abdominales', '', 'Abdominales'),
('jalon_de_rodillas', 'Jalón de Rodillas', 'Dorsales', 'banda', 'Dorsales'),
('flexiones_de_rodillas', 'Flexiones de Rodillas', 'Pecho', '', 'Pecho'),
('lsit_sostenido', 'L-Sit Sostenido', 'Abdominales', '', 'Abdominales'),
('rotacion_landmine_de_0_grados', 'Rotación landmine de 180 grados', 'Abdominales', '', 'Abdominales'),
('remo_en_base_rotativa', 'Remo en Base Rotativa', 'Espalda Superior', '', 'Espalda Superior'),
('landmine_sentadilla_y_press', 'Landmine Sentadilla y Press', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('jalon_al_pecho__agarre_cerrado', 'Jalón al Pecho - Agarre Cerrado', 'Dorsales', 'Cable', 'Dorsales'),
('jalon_al_pecho', 'Jalón al Pecho', 'Dorsales', 'Banda', 'Dorsales'),
('jalon_al_pecho_2', 'Jalón al Pecho', 'Dorsales', 'Cable', 'Dorsales'),
('jalon_al_pecho_3', 'Jalón al Pecho', 'Dorsales', 'Máquina', 'Dorsales'),
('caminata_lateral_con_banda_elastica', 'Caminata Lateral con Banda Elástica', 'Glúteos', '', 'Glúteos'),
('salto_al_cajon_lateral', 'Salto al Cajón Lateral', 'Cuádriceps', '', 'Cuádriceps'),
('elevaciones_laterales_de_pierna', 'Elevaciones Laterales de Pierna', 'Glúteos', '', 'Glúteos'),
('zancada_lateral', 'Zancada Lateral', 'Cuádriceps', '', 'Cuádriceps'),
('elevacion_laterales', 'Elevacion Laterales', 'Hombros', 'Banda', 'Hombros'),
('elevacion_laterales_2', 'Elevacion Laterales', 'Hombros', 'Cable', 'Hombros'),
('elevacion_laterales_3', 'Elevacion Laterales', 'Hombros', 'Mancuerna', 'Hombros'),
('elevacion_laterales_4', 'Elevacion Laterales', 'Hombros', 'Máquina', 'Hombros'),
('sentadilla_lateral', 'Sentadilla Lateral', 'Cuádriceps', '', 'Cuádriceps'),
('extension_de_pierna_2', 'Extensión de Pierna', 'Cuádriceps', '', 'Cuádriceps'),
('press_de_piernas', 'Press de Piernas', 'Cuádriceps', '', 'Cuádriceps'),
('press_de_piernas_sentado', 'Press de Piernas Sentado', 'Cuádriceps', '', 'Cuádriceps'),
('puente_parcial_de_gluteos', 'Puente parcial de glúteos', 'Glúteos', 'con barra', 'Glúteos'),
('sentadilla_con_pausa', 'Sentadilla con Pausa', 'Cuádriceps', 'Barra', 'Cuádriceps'),
('remo_pendlay', 'Remo Pendlay', 'Espalda Superior', 'Barra', 'Espalda Superior'),
('sentadilla_pendulo', 'Sentadilla Péndulo', 'Cuádriceps', 'Máquina', 'Cuádriceps'),
('flexion_en_pica_hombros_pilates', 'Flexión en Pica Hombros Pilates', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('curl_pinwheel', 'Curl pinwheel', 'Bíceps', 'mancuerna', 'Bíceps'),
('sentadilla_a_una_pierna', 'Sentadilla a una Pierna', 'Cuádriceps', '', 'Cuádriceps'),
('plancha', 'Plancha', 'Abdominales', '', 'Abdominales'),
('flexiones_en_plancha', 'Flexiones en Plancha', 'Pecho', '', 'Pecho'),
('curl_con_disco', 'Curl con disco', 'Bíceps', '', 'Bíceps'),
('elevacion_frontal_con_disco', 'Elevación Frontal con Disco', 'Hombros', '', 'Hombros'),
('prensa_de_placas', 'Prensa de placas', 'Pecho', '', 'Pecho'),
('apreton_con_disco', 'Apretón con disco', 'Pecho', 'Svend Press', 'Pecho'),
('power_clean', 'Power Clean', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('power_snatch', 'Power Snatch', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('curl_predicador', 'Curl predicador', 'Bíceps', 'barra', 'Bíceps'),
('curl_predicador_2', 'Curl predicador', 'Bíceps', 'mancuerna', 'Bíceps'),
('curl_predicador_3', 'Curl predicador', 'Bíceps', 'máquina', 'Bíceps'),
('presione_debajo', 'Presione debajo', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('dominada', 'Dominada', 'Dorsales', '', 'Dorsales'),
('dominada_2', 'Dominada', 'Dorsales', 'Asistida', 'Dorsales'),
('dominada_3', 'Dominada', 'Dorsales', 'Banda', 'Dorsales'),
('dominada_4', 'Dominada', 'Dorsales', 'Con Peso Añadido', 'Dorsales'),
('pull_over', 'Pull Over', 'Dorsales', '', 'Dorsales'),
('pullover', 'Pullover', 'Dorsales', 'Máquina', 'Dorsales'),
('empuje_de_fuerza', 'Empuje de Fuerza', 'Hombros', '', 'Hombros'),
('flexiones', 'Flexiones', 'Pecho', '', 'Pecho'),
('flexiones_2', 'Flexiones', 'Pecho', 'Agarre Cerrado', 'Pecho'),
('flexiones_de_brazos', 'Flexiones de Brazos', 'Pecho', 'Con Peso Agregado', 'Pecho'),
('peso_muerto_parcial_desde_el_rack', 'Peso muerto parcial desde el rack', 'Espalda Superior', '', 'Espalda Superior'),
('vuelos_posteriores_2', 'Vuelos Posteriores', 'Hombros', 'Cable', 'Hombros'),
('vuelos_invertidos_para_deltoides_posteriores', 'Vuelos invertidos para deltoides posteriores', 'Hombros', 'mancuerna', 'Hombros'),
('vuelos_posteriores_3', 'Vuelos Posteriores', 'Hombros', 'Máquina', 'Hombros'),
('patada_trasera', 'Patada trasera', 'Glúteos', 'máquina', 'Glúteos'),
('remo_renegado', 'Remo Renegado', 'Espalda Superior', '', 'Espalda Superior'),
('crunch_inverso', 'Crunch Inverso', 'Abdominales', '', 'Abdominales'),
('curl_invertido', 'Curl Invertido', 'Bíceps', 'Barra', 'Bíceps'),
('curl_invertido_2', 'Curl Invertido', 'Bíceps', 'Cable', 'Bíceps'),
('curl_invertido_3', 'Curl Invertido', 'Bíceps', 'Mancuerna', 'Bíceps'),
('vuelos_posteriores_a_un_brazo', 'Vuelos Posteriores a Un Brazo', 'Hombros', 'Cable', 'Hombros'),
('curl_de_concentracion_invertido', 'Curl de Concentración Invertido', 'Bíceps', '', 'Bíceps'),
('pulldown_lateral_con_agarre_inverso', 'Pulldown Lateral con Agarre Inverso', 'Dorsales', 'Cable', 'Dorsales'),
('hiperextension_inversa', 'Hiperextensión Inversa', 'Glúteos', '', 'Glúteos'),
('zancada_invertida', 'Zancada Invertida', 'Cuádriceps', '', 'Cuádriceps'),
('zancada_invertida_2', 'Zancada Invertida', 'Cuádriceps', 'Barra', 'Cuádriceps'),
('zancada_invertida_3', 'Zancada Invertida', 'Cuádriceps', 'Mancuerna', 'Cuádriceps'),
('plancha_inversa', 'Plancha Inversa', 'Abdominales', '', 'Abdominales'),
('fondos_en_anillas', 'Fondos en Anillas', 'Pecho', '', 'Pecho'),
('flexion_en_anillas', 'Flexión en anillas', 'Pecho', '', 'Pecho'),
('peso_muerto_rumano', 'Peso Muerto Rumano', 'Isquiotibiales', 'Barra', 'Isquiotibiales'),
('peso_muerto_rumano_2', 'Peso Muerto Rumano', 'Isquiotibiales', 'Mancuerna', 'Isquiotibiales'),
('curl_de_biceps_con_cable', 'Curl de Bíceps con Cable', 'Bíceps', '', 'Bíceps'),
('jalon_con_cuerda_de_brazos_rectos', 'Jalón con cuerda de brazos rectos', 'Dorsales', '', 'Dorsales'),
('maquina_de_remo', 'Máquina de Remo', 'Cardio', '', 'Cardio'),
('correr', 'Correr', 'Cardio', '', 'Cardio'),
('elevacion_de_gemelos_sentado', 'Elevación de Gemelos Sentado', 'Gemelos', '', 'Gemelos'),
('aperturas_de_pecho_sentado', 'Aperturas de Pecho Sentado', 'Pecho', 'Cable', 'Pecho'),
('maquina_para_fondos_sentado', 'Máquina para Fondos Sentado', 'Tríceps', '', 'Tríceps'),
('curl_de_biceps_inclinado', 'Curl de Bíceps Inclinado', 'Bíceps', 'Mancuerna', 'Bíceps'),
('vuelos_laterales_sentado', 'Vuelos Laterales Sentado', 'Hombros', 'Mancuerna', 'Hombros'),
('curl_de_pierna_sentado', 'Curl de Pierna Sentado', 'Isquiotibiales', '', 'Isquiotibiales'),
('press_de_hombros_sentado', 'Press de Hombros Sentado', 'Hombros', 'Barra', 'Hombros'),
('curl_de_muneca_palmas_arriba', 'Curl de Muñeca Palmas arriba', 'Antebrazos', '', 'Antebrazos'),
('remo_sentado', 'Remo Sentado', 'Espalda Superior', 'Máquina', 'Espalda Superior'),
('press_de_hombros_sentado_2', 'Press de Hombros Sentado', 'Hombros', 'Máquina', 'Hombros'),
('triceps_sentado', 'Tríceps Sentado', 'Tríceps', '', 'Tríceps'),
('curl_de_extension_de_muneca', 'Curl de Extensión de Muñeca', 'Antebrazos', 'Barra', 'Antebrazos'),
('press_de_hombros', 'Press de Hombros', 'Hombros', 'Mancuerna', 'Hombros'),
('press_de_hombros_2', 'Press de Hombros', 'Hombros', 'Máquina de Discos', 'Hombros'),
('flexion_de_brazos_tocando_hombro', 'Flexión de Brazos Tocando Hombro', 'Hombros', '', 'Hombros'),
('encogimiento_de_hombros', 'Encogimiento de Hombros', 'Trapecio', 'Barra', 'Trapecio'),
('encogimiento_de_hombros_2', 'Encogimiento de Hombros', 'Trapecio', 'Cable', 'Trapecio'),
('encogimiento_de_hombros_3', 'Encogimiento de Hombros', 'Trapecio', 'Mancuerna', 'Trapecio'),
('encogimientos', 'Encogimientos', 'Trapecio', 'Máquina', 'Trapecio'),
('encogimiento_de_hombros_4', 'Encogimiento de Hombros', 'Trapecio', 'Máquina Smith', 'Trapecio'),
('flexion_lateral', 'Flexión Lateral', 'Abdominales', '', 'Abdominales'),
('curva_lateral', 'Curva Lateral', 'Abdominales', 'Mancuerna', 'Abdominales'),
('plancha_lateral', 'Plancha Lateral', 'Abdominales', '', 'Abdominales'),
('cables_cruzados_de_un_solo_brazo', 'Cables Cruzados de Un Solo Brazo', 'Pecho', '', 'Pecho'),
('jalon_de_remo_a_un_brazo', 'Jalón de Remo a Un Brazo', 'Espalda Superior', '', 'Espalda Superior'),
('curl_a_un_brazo', 'Curl a un Brazo', 'Bíceps', 'Cable', 'Bíceps'),
('landmine_press_a_un_brazo', 'Landmine Press a Un Brazo', 'Hombros', 'Barra', 'Hombros'),
('jalon_al_pecho_a_un_brazo', 'Jalón al Pecho a Un Brazo', 'Dorsales', '', 'Dorsales'),
('elevacion_lateral_a_un_brazo', 'Elevación Lateral a un Brazo', 'Hombros', 'Cable', 'Hombros'),
('extension_de_triceps_de_un_brazo', 'Extensión de Tríceps de un Brazo', 'Tríceps', 'Mancuerna', 'Tríceps'),
('extension_de_triceps_a_un_brazo', 'Extensión de Tríceps a un Brazo', 'Tríceps', 'Cable', 'Tríceps'),
('extensiones_a_una_pierna', 'Extensiones a Una Pierna', 'Cuádriceps', '', 'Cuádriceps'),
('puente_de_gluteos_con_una_pierna', 'Puente de Glúteos con Una Pierna', 'Glúteos', '', 'Glúteos'),
('elevacion_de_cadera_a_una_pierna', 'Elevación de Cadera a Una Pierna', 'Glúteos', '', 'Glúteos'),
('impulso_de_cadera_a_una_pierna', 'Impulso de Cadera a una Pierna', 'Glúteos', 'Mancuerna', 'Glúteos'),
('press_a_una_pierna', 'Press a Una Pierna', 'Cuádriceps', '', 'Cuádriceps'),
('peso_muerto_rumano_a_una_pierna', 'Peso Muerto Rumano a Una Pierna', 'Isquiotibiales', 'Barra', 'Isquiotibiales'),
('peso_muerto_rumano_a_una_pierna_2', 'Peso Muerto Rumano a Una Pierna', 'Isquiotibiales', 'Mancuerna', 'Isquiotibiales'),
('elevacion_de_gemelos_a_una_pierna', 'Elevación de Gemelos a Una Pierna', 'Gemelos', '', 'Gemelos'),
('elevacion_de_gemelos_a_una_pierna_2', 'Elevación de Gemelos a Una Pierna', 'Gemelos', 'Barra', 'Gemelos'),
('elevacion_de_gemelos_a_una_pierna_3', 'Elevación de Gemelos a Una Pierna', 'Gemelos', 'mancuerna', 'Gemelos'),
('elevacion_de_gemelos_a_una_pierna_4', 'Elevación de Gemelos a Una Pierna', 'Gemelos', 'Máquina', 'Gemelos'),
('sentadilla_sissy', 'Sentadilla Sissy', 'Cuádriceps', 'Con Peso', 'Cuádriceps'),
('sit_up', 'Sit Up', 'Abdominales', '', 'Abdominales'),
('sit_up_2', 'Sit Up', 'Abdominales', 'Con Peso Añadido', 'Abdominales'),
('patinaje', 'Patinaje', 'Cardio', '', 'Cardio'),
('esqui', 'Esquí', 'Cardio', '', 'Cardio'),
('press_frances', 'Press Francés', 'Tríceps', 'Barra', 'Tríceps'),
('press_frances_2', 'Press Francés', 'Tríceps', 'Mancuerna', 'Tríceps'),
('empuje_de_trineo', 'Empuje de Trineo', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('snatch', 'Snatch', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('snowboarding', 'Snowboarding', 'Cardio', '', 'Cardio'),
('curl_arana', 'Curl Araña', 'Bíceps', 'Barra', 'Bíceps'),
('curl_arana_2', 'Curl Araña', 'Bíceps', 'Mancuerna', 'Bíceps'),
('spiderman', 'Spiderman', 'Abdominales', '', 'Abdominales'),
('spinning', 'Spinning', 'Cardio', '', 'Cardio'),
('split_jerk', 'Split Jerk', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('sentadilla_split', 'Sentadilla Split', 'Cuádriceps', 'Mancuerna', 'Cuádriceps'),
('sprints', 'Sprints', 'Cardio', '', 'Cardio'),
('sentadilla', 'Sentadilla', 'Cuádriceps', 'Banda', 'Cuádriceps'),
('sentadilla_2', 'Sentadilla', 'Cuádriceps', 'Barra', 'Cuádriceps'),
('sentadilla_3', 'Sentadilla', 'Cuádriceps', 'Peso Corporal', 'Cuádriceps'),
('sentadilla_4', 'Sentadilla', 'Cuádriceps', 'Mancuerna', 'Cuádriceps'),
('sentadilla_5', 'Sentadilla', 'Cuádriceps', 'Máquina', 'Cuádriceps'),
('sentadilla_6', 'Sentadilla', 'Cuádriceps', 'Máquina Smith', 'Cuádriceps'),
('sentadilla_7', 'Sentadilla', 'Cuádriceps', 'Suspensión', 'Cuádriceps'),
('sentadilla_con_remo', 'Sentadilla con Remo', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('patada_de_gluteo_con_cable', 'Patada de Glúteo con Cable', 'Glúteos', '', 'Glúteos'),
('elevacion_de_gemelos_de_pie', 'Elevación de Gemelos de Pie', 'Gemelos', '', 'Gemelos'),
('elevacion_de_gemelos_de_pie_2', 'Elevación de Gemelos de Pie', 'Gemelos', 'Barra', 'Gemelos'),
('elevacion_de_gemelos_de_pie_3', 'Elevación de Gemelos de Pie', 'Gemelos', 'Mancuerna', 'Gemelos'),
('elevacion_de_gemelos_de_pie_4', 'Elevación de Gemelos de Pie', 'Gemelos', 'Máquina', 'Gemelos'),
('elevacion_de_gemelos_de_pie_5', 'Elevación de Gemelos de Pie', 'Gemelos', 'Smith', 'Gemelos'),
('curls_de_piernas_de_pie', 'Curls de Piernas de Pie', 'Isquiotibiales', '', 'Isquiotibiales'),
('press_militar_de_pie', 'Press Militar de Pie', 'Hombros', 'Barra', 'Hombros'),
('da_un_paso_adelante', 'Da un paso adelante', 'Cuádriceps', '', 'Cuádriceps'),
('dominada_perfecta', 'Dominada Perfecta', 'Dorsales', 'Gironda', 'Dorsales'),
('jalon_de_dorsales_con_brazos_rectos', 'Jalón de dorsales con brazos rectos', 'Dorsales', 'polea', 'Dorsales'),
('peso_muerto_piernas_estiradas', 'Peso Muerto Piernas Estiradas', 'Isquiotibiales', '', 'Isquiotibiales'),
('estiramiento', 'Estiramiento', 'Otro', '', 'Otro'),
('peso_muerto_sumo', 'Peso Muerto Sumo', 'Glúteos', '', 'Glúteos'),
('sentadilla_sumo', 'Sentadilla Sumo', 'Cuádriceps', '', 'Cuádriceps'),
('sentadilla_sumo_2', 'Sentadilla Sumo', 'Cuádriceps', 'Barra', 'Cuádriceps'),
('sentadilla_sumo_3', 'Sentadilla Sumo', 'Cuádriceps', 'Mancuerna', 'Cuádriceps'),
('sentadilla_sumo_4', 'Sentadilla Sumo', 'Cuádriceps', 'Pesa Rusa', 'Cuádriceps'),
('superman', 'Superman', 'Espalda Baja', '', 'Espalda Baja'),
('natacion', 'Natación', 'Cardio', '', 'Cardio'),
('remo_en_punta', 'Remo en Punta', 'Espalda Superior', '', 'Espalda Superior'),
('thruster', 'Thruster', 'Cuerpo Entero', 'Barra', 'Cuerpo Entero'),
('thruster_2', 'Thruster', 'Cuerpo Entero', 'Pesa Rusa', 'Cuerpo Entero'),
('toque_de_pies_abdominales', 'Toque de Pies abdominales', 'Abdominales', '', 'Abdominales'),
('pies_a_la_barra', 'Pies a la Barra', 'Abdominales', '', 'Abdominales'),
('rotacion_de_torso', 'Rotación de Torso', 'Abdominales', '', 'Abdominales'),
('cinta', 'Cinta', 'Cardio', '', 'Cardio'),
('fondo_de_triceps', 'Fondo de Tríceps', 'Tríceps', '', 'Tríceps'),
('fondo_de_triceps_2', 'Fondo de Tríceps', 'Tríceps', 'Asistido', 'Tríceps'),
('fondo_de_triceps_3', 'Fondo de Tríceps', 'Tríceps', 'Con Peso Añadido', 'Tríceps'),
('extension_de_triceps', 'Extensión de Tríceps', 'Tríceps', 'Barra', 'Tríceps'),
('extension_de_triceps_2', 'Extensión de Tríceps', 'Tríceps', 'Cable', 'Tríceps'),
('extension_de_triceps_3', 'Extensión de Tríceps', 'Tríceps', 'Mancuerna', 'Tríceps'),
('extension_de_triceps_4', 'Extensión de Tríceps', 'Tríceps', 'Máquina', 'Tríceps'),
('extension_triceps', 'Extensión Tríceps', 'Tríceps', 'Suspensión', 'Tríceps'),
('extension_de_triceps_atras', 'Extensión de Tríceps Atrás', 'Tríceps', 'Cable', 'Tríceps'),
('patada_de_triceps', 'Patada de Tríceps', 'Tríceps', '', 'Tríceps'),
('extension_de_triceps_en_polea', 'Extensión de tríceps en polea', 'Tríceps', '', 'Tríceps'),
('triceps_con_polea', 'Tríceps con Polea', 'Tríceps', '', 'Tríceps'),
('jalon_de_triceps_con_cuerda', 'Jalón de tríceps con cuerda', 'Tríceps', '', 'Tríceps'),
('remo_vertical', 'Remo Vertical', 'Hombros', 'Barra', 'Hombros'),
('remo_al_menton', 'Remo al mentón', 'Hombros', 'Cable', 'Hombros'),
('remo_vertical_2', 'Remo Vertical', 'Hombros', 'Mancuerna', 'Hombros'),
('traccion_vertical', 'Tracción vertical', 'Dorsales', 'máquina', 'Dorsales'),
('curl_de_camarero', 'Curl de camarero', 'Bíceps', 'mancuerna', 'Bíceps'),
('caminar', 'Caminar', 'Cardio', '', 'Cardio'),
('zancadas_caminando', 'Zancadas Caminando', 'Cuádriceps', '', 'Cuádriceps'),
('zancadas_caminando_2', 'Zancadas Caminando', 'Cuádriceps', 'Mancuerna', 'Cuádriceps'),
('lanzamientos_de_balon', 'Lanzamientos de Balón', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('sentadilla_en_pared', 'Sentadilla en Pared', 'Cuádriceps', '', 'Cuádriceps'),
('calentamiento', 'Calentamiento', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('dominada_abierta', 'Dominada Abierta', 'Dorsales', '', 'Dorsales'),
('press_de_triceps_con_codos_abiertos', 'Press de tríceps con codos abiertos', 'Tríceps', 'mancuerna', 'Tríceps'),
('rodillo_de_antebrazos', 'Rodillo de Antebrazos', 'Antebrazos', '', 'Antebrazos'),
('yoga', 'Yoga', 'Cuerpo Entero', '', 'Cuerpo Entero'),
('sentadilla_zercher', 'Sentadilla Zercher', 'Cuádriceps', '', 'Cuádriceps'),
('curl_zottman', 'Curl Zottman', 'Bíceps', 'Mancuerna', 'Bíceps');
